contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #phipseqtpvac channel"
    url: https://nfcore.slack.com/channels/phipseqtpvac
    about: Discussion about the nf-core/phipseqtpvac pipeline
